### ISSUE TITLE
Command `Silicon` not found after loading `nvim-silicon`

### ISSUE THREAD

**Issue by thiagodebastos** [michaelrommel/nvim-silicon#12]
I get this error on MacOS on an M2.

I have tried installing silicon via `homebrew` and via `cargo`. I have also tried setting the `command` property to point to the homebrew and cargo binary directly, but this issue still persists.

For example, the following did not help:

```
command = "/opt/homebrew/bin/silicon",
```

In both cases, I tested in the terminal and `silicon` is in fact in my path.

**Comment by michaelrommel** [comment]
Hi,

this is very strange. I have tried this with several installations and had no problems. I have refactored the code a lot today and added a debug = true option that you could use to track down the error. Can you try that please:

```
-- create code images
local opts = {
	"michaelrommel/nvim-silicon",
	dir = '/Users/rommel/Software/michael/nvim-silicon',
	lazy = true,
	cmd = "Silicon",
	opts = {
		debug = true,
		disable_defaults = true,
		-- command = "/opt/homebrew/bin/silicon",
		-- command = "/Users/rommel/.local/share/mise/installs/rust/latest/bin/silicon"
	}
}
```

and report back, what message you see? Or try again the command parameter, as commented out above...

Thanks,

  Michael.

**Comment by michaelrommel** [comment]
Hello,

have you had a chance to try this with `debug = true`? Would like to close that topic soon!

Thanks!

  Michael.

**Comment by michaelrommel** [comment]
No problem and don't worry! I just wanted to make sure everyone is happy...

The Lazy package manager has different ways of specifying the configuration. The simplest method is just to specify an `opts` table on the same level as the `cmd` specification. Lazy then automatically calls the `config()` function with this as argument:

| Property | Type | Description  |
|-|-|-|
opts | table or fun(LazyPlugin, opts:table) | opts should be a table (will be merged with parent specs), return a table (replaces parent specs) or should change a table. The table will be passed to the Plugin.config() function. Setting this value will imply Plugin.config()

I used different variations in the README to show different variants. But maybe that was more confusing than helpful...

In the last example from your last comment the part:

```
{
  - - Configuration here, or leave empty to use defaults
  font = "VictorMono NF=34;Noto Emoji=34"
}
```

is actually the `opts` table...

Glad that it works for you now! Have a good day!

  Michael.
