### ISSUE TITLE
Is it possible pass some options when using command :Silicon just like vim-silicon

### ISSUE THREAD

**Issue by JiuRanYa** [michaelrommel/nvim-silicon#17]
Just like this

```vim
:Silicon --language=js
```

Pass some options when code higlighting not work;

By the way, awasome plugin for me!

**Comment by michaelrommel** [comment]
Thanks for the suggestion, I will look into it!

**Comment by JiuRanYa** [comment]
Sorry about replying now.

**Comment by michaelrommel** [comment]
@JiuRanYa thank you very much for the explanation. I understand now the use case. Why I am hesitating is, that I have no good way to parse those arguments properly. If I just take them verbatim without parsing, they would conflict with other default arguments and the command would fail. So I would need to understand exactly which arguments they override and delete those from the constructed command line. It would make the code more complex and testing it would be harder and harder.

```lua
language = function()
	local lang = nil
	if vim.bo.filetype == nil or vim.bo.filetype == "" then
		-- if we cannot determine the filetype supply no default argument
		lang = vim.fn.input("Language: ", "")
	else
		-- otherwise have the filetype as preset for most cases
		lang = vim.fn.input("Language: ", vim.bo.filetype)
	end
	if lang and lang ~= "" then
		return lang
	else
		-- dialog was cancelled
		return "md"
	end
end,
```

Could you try this in your plugin setup? This would always prompt you for a language with the filetype as default (but you could change that as well). In your case you can just press backspace three times, type ts and return. This is six keystrokes.

Or you can press Ctrl-f o ts <return> which is 5 keystrokes. Which is a lot less than if you had to type out the command line arguments yourself.

At the moment the code checks for function()s only for "language", "output", "window_title" and "line_offset", so if there are other options, where you would like to have such an input function, let me know. 

Can you give it a try, please? I am really trying to keep the code and tests maintainable.

Thanks a lot!

  Michael.

**Comment by JiuRanYa** [comment]
Thanks fro your reply. I'll try later.

**Comment by michaelrommel** [comment]
Hi,

I am now using the above mentioned language functions myself on a daily basis and found that this would cover probably most people's need. Feel free to comment in the newly created discussion of release v1.0.0 if you are unhappy with my decision!

Also as I said: please raise an issue, if you need further options to accept lua functions instead of strings/booleans/numbers. I am happy to amend that if needed!

Thanks for your suggestions and the constructive discussion!

  Michael.
