### ISSUE TITLE
How do i set the ouput directory

### ISSUE THREAD

**Issue by brushy501** [michaelrommel/nvim-silicon#22]
Hello, thanks for the great plugin. It works well on windows 10 and i love it.
Just a small question/request, how can i specify the output directory for the snapshot.
It currently saves to the nvim folder and i will like to change it to another location.
Thanks in advance. 😀

**Comment by michaelrommel** [comment]
Hi,

in your config, put an 'output' function and specify the directory, where you would like to have the screenshots:

```
output = function()
    return "C:\\temp\\" .. os.date("!%Y-%m-%dT%H-%M-%SZ") .. "_code.png"
end
```

Something like that, you may have to experiment with the escape backslashes (I do not use Windows, so idk). Let me know, if that works for you.

Thanks,

  Michael.

**Comment by brushy501** [comment]
Thanks i will try this out and let you know

**Comment by brushy501** [comment]
Thanks. It works. Now to get more code snapshots. Thanks a lot for the plugin.
