### ISSUE TITLE
Add 'neovim-plugin' as topic to the GitHub repository

### ISSUE THREAD

**Issue by Frestein** [michaelrommel/nvim-silicon#23]
I would like to request the addition of the 'neovim-plugin' tag to this repository. This tag is necessary for the plugin to be listed on [dotfyle.com](https://dotfyle.com/), which is a valuable resource for Neovim users.

Please consider tagging the repository accordingly.

![image](https://github.com/user-attachments/assets/7f0737ae-930e-407f-8822-6a3b36497b97)

**Comment by michaelrommel** [comment]
done. Thanks for the suggestion, I wasn't aware of that.

**Comment by Frestein** [comment]
> done. Thanks for the suggestion, I wasn't aware of that.

Thank you!
https://dotfyle.com/plugins/michaelrommel/nvim-silicon
