### ISSUE TITLE
Relative Line Numbers

### ISSUE THREAD

**Issue by Kyle-Mendes** [michaelrommel/nvim-silicon#3]
It would be great if there was an option to have the line numbers match the line numbers in the snippet!

**Comment by michaelrommel** [comment]
Implemented in the last commit. The README shows the example, the default is still the number "1".

**Comment by michaelrommel** [comment]
New vs. old:
![2023-09-14T18-04-33_code](https://github.com/michaelrommel/nvim-silicon/assets/919935/b58a8d30-9d0a-4826-bbdc-bf78dd2d3e63)
![2023-09-14T18-05-19_code](https://github.com/michaelrommel/nvim-silicon/assets/919935/34a11382-f6b3-4961-9d2b-bdf0277a6eae)

**Comment by Kyle-Mendes** [comment]
🙏 Thanks!
