### ISSUE TITLE
Feature request: space after line-numbers

### ISSUE THREAD

**Issue by BWindey** [michaelrommel/nvim-silicon#6]
Hi, I'm really like this tool after seeing it from "Dreams of Code" Youtube video. I've set it all up, configured it with Catppuccin, and now I'm making screenshots that are prettier then a colourful sunset. 

Anyways, the only "issue" I have left, is that the line-numbers appear a bit to close to the lines for my liking. Would it be possible to add something to the options to control how much space is between the numbers and the start of the text?
It could be something like
```lua
    line_number_pad = 0        -- (default?)
```

Thanks a lot for considering this!

For reference:
![image](https://github.com/michaelrommel/nvim-silicon/assets/93756910/5001db80-3594-43ac-b19f-19b48ea6a290)
![image](https://github.com/michaelrommel/nvim-silicon/assets/93756910/534fd4e2-18ab-4513-a79b-fa4943cc868b)

(2nd image I turned off `gobble` and placed a space in front of the line)

**Comment by michaelrommel** [comment]
Hello, thanks for your suggestion! I can implement that for sure with the blanks. Other spacings in pixel units or so would be subject to a change to the underlying `silicon` rust tool. Will look at it in the next days!

**Comment by michaelrommel** [comment]
Hello,

can you check out the latest version, please? I have added a `num_separator` option, that you can use to insert arbitrary characters between the number column and the code. You can set this to a single blank, as you had it in your example, but also choose to do something like below.

I hope that matches your expectation, then feel free to close this issue.

![2024-03-01T10-07-26_code](https://github.com/michaelrommel/nvim-silicon/assets/919935/44d82e6f-3938-4cd8-af00-5e30e9726388)

Thanks for the suggestion,

  Michael.

**Comment by BWindey** [comment]
That's exactly what I wished! Thanks for the swift reply and fix!

![image](https://github.com/michaelrommel/nvim-silicon/assets/93756910/be87928a-13c1-49a5-be6e-20df28e70346)
