### ISSUE TITLE
Issue with gobble=true on v0.9.5 neovim

### ISSUE THREAD

**Issue by noenthu** [michaelrommel/nvim-silicon#7]
When running the command Silicon on an open file, I encounter the following error. 

> nvim-silicon/lua/silicon.lua:86: attempt to call field 'gobble' (a nil value)

![image](https://github.com/michaelrommel/nvim-silicon/assets/989601/876d0c68-d617-4aef-9218-e6673fa4e4c5)

With gobble disabled, the screenshot functionality works as expected.

**Comment by michaelrommel** [comment]
Dear Vivek,

can you please update and try again. I have been moving the required utils package into a silicon namespace. This should avoid the clashes with another utils package, that you experienced. Please let me know if this works for you. Sorry!!

  Michael.

**Comment by noenthu** [comment]
The namespace change seems to have resolved the issue. Thank you!
