### ISSUE TITLE
Doesn't work with Silicon configuration file

### ISSUE THREAD

**Issue by uncenter** [michaelrommel/nvim-silicon#9]
I get an error about having multiple of the same argument/option provided with the default configuration because I am also using a silicon configuration file (which is a text file, newline delimited, of args to pass to silicon). Being able to disable all default arguments from being passed in would be really helpful!

**Comment by michaelrommel** [comment]
Hi,

I have implemented your suggestion. You should be able now to use your config file. But please make sure, that you do not have conflicting or double settings now in neovim and the silicon config file.

Please close the issue, if satisfied.

Thanks,

  Michael.

**Comment by uncenter** [comment]
I think the `output` and `language` options should also be part of the mandatory defaults that are not disabled by `disable_defaults`. Hard to use it without those, and it doesn't really make sense to put them in the config file... and I also get strange errors when trying to use those functions in my options.

**Comment by michaelrommel** [comment]
Please share the config.

**Comment by uncenter** [comment]
```lua
return {
	"michaelrommel/nvim-silicon",
	lazy = true,
	cmd = "Silicon",
	opts = {
		disable_defaults = true,
		language = function()
			return vim.bo.filetype
		end,
		output = function()
			return "./" .. os.date("!%Y-%m-%dT%H-%M-%S") .. "_code.png"
		end,
	},
}
```

**Comment by michaelrommel** [comment]
That should now be fixed in the latest version. Thanks for reporting! Can you try again with this config?

**Comment by uncenter** [comment]
Ahh it works perfectly! Thank you so much.

**Comment by michaelrommel** [comment]
Thanks for your patience - I introduced a bug when I tried to implement the fallback from `filetype` to `extension`, because fortran was not working... Glad that it is solved for you now!
